### ISSUE TITLE
DMM Optix support?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIAGameWorks/Displacement-MicroMap-Toolkit#1]
Hi,
Interest on testing DMM on Optix..
Hope it’s planed..
Opened issue so can be notified when it’s released.. :-)

**Comment by NBickford-NV** [comment]
Hi Oscar - we released OptiX Ray Tracing SDK 7.7.0 today, which adds APIs for displaced micro-meshes!

You can download OptiX 7.7 and view its release notes here: https://developer.nvidia.com/designworks/optix/download .

OptiX 7.7 also includes the `optixDisplacedMicromesh` sample, which shows how to use the new OptiX DMM APIs.

Thanks for the question, and hope this helps!

**Comment by oscarbg** [comment]
Many thanks! Will give a try..
@NeilBickford-NV Just a question does Optix support Ada SER (shader reordering) functionality?
Should be a simple addition (vulkan SER ext shows that), but can’t find it mentioned in either Optix 7.6 or 7.7 rn which are the post Ada launch Optix releases.. coming it for Optix 8.0?
Strange if it’s not yet, as should help more perf on Ada for Blender and other Optix renderers like PBRT v4..
Thanks..
