### ISSUE TITLE
[Runtime Error]Micro-Mesh displacement not supported

### ISSUE THREAD

**Issue by lyd405121** [NVIDIAGameWorks/Displacement-MicroMap-Toolkit#3]
## Description
- Successfully build using cmake
- Run the Sample
- Failed when check vulkan extesion

![error](https://user-images.githubusercontent.com/16344694/227859827-3a104a41-1d5a-45c6-8f92-cea3c840efdf.png)

## More info 
- windows10
- 2070 super

## Background 
- After reading serveral GTC reports， I really like this tech most
- Since the weakness for raytracing is handle with transparency and displament
- Moreover，parallel remesher is also what I am searching for

**Comment by pknowlesnv** [comment]
Glad you like the tech, thanks :). This error looks to be coming from [`mini_samples/dmm_displacement/src/dmm_raytrace.cpp`](https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/blob/0341676840b150a58fff3abec93168f49612cdcc/mini_samples/dmm_displacement/src/dmm_raytrace.cpp#L789)

```
  if(!app->getContext()->hasDeviceExtension(VK_NV_DISPLACEMENT_MICROMAP_EXTENSION_NAME))
  {
    LOGE("ERROR: Micro-Mesh displacement not supported");
    exit(1);
  }
```

This would happen if the driver is missing `VK_NV_displacement_micromap` support. Can you try updating to the latest vulkan beta driver at https://developer.nvidia.com/vulkan-driver?

**Comment by lyd405121** [comment]
> Glad you like the tech, thanks :). This error looks to be coming from [`mini_samples/dmm_displacement/src/dmm_raytrace.cpp`](https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/blob/0341676840b150a58fff3abec93168f49612cdcc/mini_samples/dmm_displacement/src/dmm_raytrace.cpp#L789)
> 
> ```
>   if(!app->getContext()->hasDeviceExtension(VK_NV_DISPLACEMENT_MICROMAP_EXTENSION_NAME))
>   {
>     LOGE("ERROR: Micro-Mesh displacement not supported");
>     exit(1);
>   }
> ```
> 
> This would happen if the driver is missing `VK_NV_displacement_micromap` support. Can you try updating to the latest vulkan beta driver at https://developer.nvidia.com/vulkan-driver?

- Beta driver, Get it.
## Another question
- I notice that "VK_NV_displacement_micromap" is **NV** extension, so it can only be used with nvidia gpu.
- While the [OMM SDK](https://github.com/NVIDIAGameWorks/Opacity-MicroMap-SDK) which I have already played for weeks, need  VK_EXT_OPACITY_micromap imply this is a [common extension](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#resources-micromaps).

![vulkan](https://user-images.githubusercontent.com/16344694/228712393-e5b94852-9163-4cbc-84c0-5724db848ae4.png)

- Is that right?

**Comment by pixeljetstream** [comment]
In theory other vendors could implement the extension as is, even if it is a vendor extension, but typically it needs a bit of a standardization process. Right now NVIDIA is the only vendor implementing it. Sites like [vulkan.gpuinfo.org](https://vulkan.gpuinfo.org/) allow you to see what is available in the field.

**Comment by lyd405121** [comment]
> In theory other vendors could implement the extension as is, even if it is a vendor extension, but typically it needs a bit of a standardization process. Right now NVIDIA is the only vendor implementing it. Sites like [vulkan.gpuinfo.org](https://vulkan.gpuinfo.org/) allow you to see what is available in the field.

Thank you for your kind imformation :)
