### ISSUE TITLE
Micromesh rasterization

### ISSUE THREAD

**Issue by fanghao6666** [NVIDIAGameWorks/Displacement-MicroMap-Toolkit#4]
"The rasterization of micromeshes, especially compressed is a bit of a more complex topic on its own. Therefore there will be a future dedicated sample that goes into the details of how it works and showcases more features, such as dynamic level-of-detail. We recommend to wait for this, rather than attempt to embed the code from the toolbox. The future sample will also provide more performant solutions and address compute-based rasterization as well."

-- When can I see the content of this section?

**Comment by pixeljetstream** [comment]
Thanks for your interest!
We are awaiting a newer beta driver that will feature some new intrinsics for SPIR-V that aid the decoding process. We don't have a firm ETA for that driver and the sample release yet. But I want to to re-iterate that it's not recommended to use the code from rasterization in this toolkit, as it will change significantly in future and is not performance optimal, nor storage optimal.

**Comment by pixeljetstream** [comment]
A dedicated sample was released here https://github.com/nvpro-samples/vk_displacement_micromaps
